<a href="https://colab.research.google.com/github/krackofficer/Numpy-Assignment-/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Assignment Practical questions

In [ ]:
## Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:

import numpy as np

# Create a 3x3 array with random integers
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns
transposed_array = array.T
print("Transposed Array:")
print(transposed_array)

Original Array:
[[ 5 11 81]
 [82 83 92]
 [81 92 58]]
Transposed Array:
[[ 5 82 81]
 [11 83 92]
 [81 92 58]]


In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
array_2 = np.arange(10)
print("\nOriginal 1D Array:")
print(array_2)

array_2_2x5 = array_2.reshape(2,5)
print("Reshaped to 2x5:")
print(array_2_2x5)

array_2_5x2 = array_2.reshape(5,2)
print("Reshaped to 5x2:")
print(array_2_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
array_3 = np.random.rand(4,4)
print("\nOriginal 4x4 Array:")
print(array_3)

bordered_array_3 = np.pad(array_3, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Border:")
print(bordered_array_3)


Original 4x4 Array:
[[0.5953285  0.90458641 0.21878722 0.99736697]
 [0.22782764 0.21384711 0.30188225 0.08121918]
 [0.57656542 0.1411792  0.51392356 0.55059957]
 [0.23734271 0.23214545 0.48330582 0.23124492]]
6x6 Array with Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5953285  0.90458641 0.21878722 0.99736697 0.        ]
 [0.         0.22782764 0.21384711 0.30188225 0.08121918 0.        ]
 [0.         0.57656542 0.1411792  0.51392356 0.55059957 0.        ]
 [0.         0.23734271 0.23214545 0.48330582 0.23124492 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
array_4 = np.arange(10, 61, 5)
print("\nArray from 10 to 60 with step 5 :")
print(array_4)


Array from 10 to 60 with step 5 :
[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.

In [ ]:
array_5 = np.array(['python', 'numpy', 'pandas'])

uppercase_5 = np.char.upper(array_5)
lowercase_5 = np.char.lower(array_5)
titlecase_5 = np.char.title(array_5)

print("\nUppercase :", uppercase_5)
print("Lowercase :", lowercase_5)
print("Titlecase :", titlecase_5)


Uppercase : ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase : ['python' 'numpy' 'pandas']
Titlecase : ['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word.

In [ ]:
array_6 = np.array(['krack', 'officer'])
spaced_array_6 = np.char.join(' ', array_6)
print("\nWords with spaces between characters :")
print(spaced_array_6)


Words with spaces between characters :
['k r a c k' 'o f f i c e r']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
array_7a = np.random.randint(1, 10, size=(2,2))
array_7b = np.random.randint(1, 10, size=(2,2))

print("\nFirst Array :")
print(array_7a)
print("Second Array :")
print(array_7b)

print("Addition:\n", array_7a + array_7b)
print("Subtraction:\n", array_7a - array_7b)
print("Multiplication:\n", array_7a * array_7b)
print("Division:\n", array_7a / array_7b)


First Array :
[[5 1]
 [7 8]]
Second Array :
[[2 8]
 [5 1]]
Addition:
 [[ 7  9]
 [12  9]]
Subtraction:
 [[ 3 -7]
 [ 2  7]]
Multiplication:
 [[10  8]
 [35  8]]
Division:
 [[2.5   0.125]
 [1.4   8.   ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity_matrix_8 = np.eye(5)
diagonal_elements_8 = np.diag(identity_matrix_8)
print("\n5x5 Identity Matrix :")
print(identity_matrix_8)
print("Diagonal Elements :")
print(diagonal_elements_8)


5x5 Identity Matrix :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements :
[1. 1. 1. 1. 1.]


In [ ]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

array_9 = np.random.randint(0, 1001, size=100)
prime_numbers_9 = np.array([num for num in array_9 if is_prime(num)])

print("\nOriginal Array :")
print(array_9)
print("Prime Numbers :")
print(prime_numbers_9)


Original Array :
[414 801 625 768 174 736 300 987 839 563 268 779 752 687 981 965 591 662
  40 609 739 206 701 403 772 635 571 403 336  15 209 678 790 223 911 121
 668 184 950 917 440 671 199 286 711 517 970  21 754   7 797 534 497 322
 572 960 300 117 432  69 484  67 285 293 717 865  59 790 296 793 476 695
 788 650  51 836 185 296 203 906 248 254 641 349 724 283 853 382  26 239
 491 154 936 541 462 269 950 691 566 342]
Prime Numbers :
[839 563 739 701 571 223 911 199   7 797  67 293  59 641 349 283 853 239
 491 541 269 691]


In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
temperatures_10 = np.random.uniform(low=20.0, high=40.0, size=30)
weekly_avg_10 = temperatures_10.reshape(5,6).mean(axis=1)

print("\nDaily Temperatures for a Month :")
print(temperatures_10)
print("Weekly Averages :")
print(weekly_avg_10)


Daily Temperatures for a Month :
[22.21465761 28.06781441 23.90799991 22.97625178 22.50412036 30.90979106
 34.92405663 39.43659301 21.96081373 33.60668149 38.46843426 24.7586746
 36.17450461 27.22035601 21.55004867 20.03357206 37.96257861 33.03385037
 36.3279209  27.31726193 33.10094818 24.28720955 32.6617565  22.65425036
 39.71646303 27.91299545 38.56787997 31.63645555 36.85248691 31.63611525]
Weekly Averages :
[25.09677252 32.19254229 29.32915172 29.3915579  34.38706603]


In [ ]:
## Thanks for this lovely project.